# Generated by Django 3.1.1 on 2024-03-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240327_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='course',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='department',
        ),
    ]
