# Generated by Django 3.1.1 on 2024-03-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20240327_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='subject',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='internresult',
            old_name='subject',
            new_name='task',
        ),
    ]
