# Generated by Django 3.1.1 on 2024-03-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20240328_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_year',
            field=models.TimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_year',
            field=models.TimeField(verbose_name=''),
        ),
    ]
