# Generated by Django 3.1.1 on 2024-03-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20240330_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_year',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
