# Generated by Django 3.1.1 on 2024-03-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20240330_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='staff',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='intern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.intern'),
        ),
    ]
