# Generated by Django 3.1.1 on 2024-04-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_interns',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='main_app.Intern'),
        ),
    ]
