# Generated by Django 3.1.1 on 2024-04-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_task_assigned_interns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_interns',
        ),
    ]
