# Generated by Django 3.1.1 on 2024-04-21 04:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_attendance_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.task'),
            preserve_default=False,
        ),
    ]
