# Generated by Django 3.1.1 on 2024-04-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_attendance_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='task',
        ),
    ]
