# Generated by Django 3.1.1 on 2024-04-21 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20240421_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.shift'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='task',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.task'),
        ),
    ]
