# Generated by Django 3.1.1 on 2024-04-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20240421_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main_app.department'),
        ),
    ]
