# Generated by Django 3.1.1 on 2024-04-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20240421_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='intern_feedback',
            field=models.TextField(blank=True),
        ),
    ]
