# Generated by Django 3.1.1 on 2024-04-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_task_intern_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff'),
        ),
    ]
