# Generated by Django 3.1.1 on 2024-05-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_intern_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff'),
        ),
    ]
