# Generated by Django 3.1.1 on 2024-05-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_task_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='staff',
        ),
    ]
